import type { ApplicationStatus, Job, MatchResult, UserJobState } from '../types'

const columns: Array<{ status: ApplicationStatus; label: string; tone: string }> = [
  { status: 'wishlist', label: '待投递', tone: '#718096' }, { status: 'applied', label: '已投递', tone: '#5278df' }, { status: 'assessment', label: '笔试 / 测评', tone: '#a96fc0' }, { status: 'interview', label: '面试中', tone: '#d98745' }, { status: 'offer', label: 'Offer', tone: '#339a73' }, { status: 'rejected', label: '未通过', tone: '#bd6262' },
]

export function PipelinePage({ jobs, matches, userJobs, onStatus, onSelect }: { jobs: Job[]; matches: Record<string, MatchResult>; userJobs: Record<string, UserJobState>; onStatus: (id: string, status: ApplicationStatus) => void; onSelect: (job: Job) => void }) {
  return <div className="standard-page"><header className="page-header"><div><div className="eyebrow"><span /> APPLICATION TRACKER</div><h1>投递看板</h1><p>把每一次尝试都认真记录，也让下一步始终清晰。</p></div></header><div className="pipeline-summary"><strong>{Object.values(userJobs).filter((item) => item.applicationStatus).length}</strong><span>个进行中的机会</span><i />本地自动保存</div><div className="kanban">{columns.map((column) => { const items = jobs.filter((job) => userJobs[job.id]?.applicationStatus === column.status); return <section className="kanban-column" key={column.status}><header><span style={{ background: column.tone }} />{column.label}<em>{items.length}</em></header><div className="kanban-list">{items.map((job) => <article key={job.id} className="pipeline-card" onClick={() => onSelect(job)}><div className="company-logo small" style={{ background: job.accent }}>{job.companyShort}</div><h3>{job.title}</h3><p>{job.companyName} · {job.location}</p><div><span className={matches[job.id].score >= 80 ? 'match-pill high' : 'match-pill'}>{matches[job.id].score}% 匹配</span><select aria-label={`更新 ${job.title} 状态`} value={column.status} onClick={(event) => event.stopPropagation()} onChange={(event) => onStatus(job.id, event.target.value as ApplicationStatus)}>{columns.map((option) => <option key={option.status} value={option.status}>{option.label}</option>)}</select></div>{userJobs[job.id]?.notes && <small>“{userJobs[job.id]?.notes}”</small>}</article>)}{items.length === 0 && <div className="column-empty">暂无岗位</div>}</div></section> })}</div></div>
}
